# Generated by Django 5.0.7 on 2024-12-29 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("courses", "0001_add_spec_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.ImageField(upload_to="", verbose_name="Файл")),
            ],
            options={
                "verbose_name": "Фото",
                "verbose_name_plural": "Фото",
            },
        ),
    ]
