# Generated by Django 5.0.7 on 2024-12-29 17:38

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0008_add_answer_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="group",
            name="date_formation",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 12, 29, 17, 38, 5, 438523, tzinfo=datetime.timezone.utc
                ),
                verbose_name="Дата образования",
            ),
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "image",
                    models.ManyToManyField(
                        blank=True, to="courses.image", verbose_name="Фото"
                    ),
                ),
                (
                    "specializations",
                    models.ManyToManyField(to="courses.specialization"),
                ),
            ],
            options={
                "verbose_name": "Статья",
                "verbose_name_plural": "Статьи",
            },
        ),
    ]
